# Generated by Django 4.1.3 on 2022-12-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=100)),
                ('signup', models.BooleanField(default=False)),
            ],
        ),
    ]
